sudo: required
services:
- docker
addons:
  ssh_known_hosts: 128.199.52.234
env:
  global:
    secure:
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in super_secret.txt.enc -out super_secret.txt
  -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 128.199.52.234\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@128.199.52.234 pwd
script:
- docker build -t scouser/docker-nodejs .
- docker run -p 8080:8080 scouser/docker-nodejs
after_script:
- docker images
