sudo: required

language: node_js
node_js:
  - 8.12.0

services:
  - docker

script:
  - docker build -t scouser/docker-nodejs .
  - docker run -p http://128.199.52.234:8080 scouser/docker-nodejs

after_script:
  - docker images
