sudo: required

language: node_js
node_js:
  - 8.12.0

services:
  - docker

before_install:
  - docker build -t scouser/docker-nodejs .
  - docker run -p http://128.199.52.234:8080 scouser/docker-nodejs
  - docker ps -a